---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${ORDER_API_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: 'target'
    script: |-
      #!/bin/bash
      mvn clean install
      mkdir -p target/defaultServer/apps
      mv manifest.yml target/
      mv server.xml target/defaultServer/
      mv target/*.war target/defaultServer/apps/
- name: DEV
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${DEV_REGION_ID}
      organization: ${DEV_ORG_NAME}
      space: ${DEV_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      cf create-service elephantsql turtle myMicroservicesSQL
      cf create-service service_discovery free myMicroservicesServiceDiscovery
      # Push app
      export CF_APP_NAME="dev-$CF_APP"
      cf push -p defaultServer
      # View logs
      #cf logs "${CF_APP_NAME}" --recent
